package bot.telegram.enums;

public enum State {
    MAIN,
    ADD_ORDER,
    FOOD_MENU,
    TO_BASKET,
    IS_MENU_NAME,
    IS_FOOD_NAME,
    IS_FOOD_TYPE,
    IS_FOOD_PRICE,
    FOOD_EDIT_MENU,
    FOOD_DELETE_MENU,
    EDIT_FOOD_NAME,
    DELETE_FOOD_NAME,
    EDITION_TYPE,
    EDITION_FOOD_NAME,
    EDITION_FOOD_PRICE,
    REMOVE_BASKET,
    REMOVE_BASKET_FOOD,
    SET_FOOD
}
